name: SpicyHolograms
version: ${project.version}
main: io.pulsarlabs.spicyholograms.SpicyHolograms
api-version: 1.18
depend:
  - ProtocolLib
authors: [ saifsuleman ]
website: https://github.com/saifsuleman
loadbefore: [ polyscript ]